services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - BASE_URL=http://localhost:8080
      - AUTH=auth
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=url
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: url
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: